"""initial schema

Revision ID: 75cb5dedd040
Revises:
Create Date: 2026-07-07 03:27:52.901215

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '75cb5dedd040'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('primary_muscle', sa.String(length=60), nullable=False),
    sa.Column('movement_pattern', sa.String(length=60), nullable=False),
    sa.Column('difficulty_level', sa.String(length=30), nullable=False),
    sa.Column('goal_tags', sa.String(length=150), nullable=False),
    sa.Column('equipment_name', sa.String(length=100), nullable=False),
    sa.Column('restriction_tags', sa.String(length=150), nullable=False),
    sa.Column('video_url', sa.String(length=500), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('default_weight_kg', sa.Float(), nullable=False),
    sa.Column('progression_step_kg', sa.Float(), nullable=False),
    sa.Column('load_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('restrictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('body_area', sa.String(length=60), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('email_confirmed', sa.Boolean(), nullable=False),
    sa.Column('token_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('user_profiles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('age', sa.Integer(), nullable=False),
    sa.Column('gender', sa.String(length=30), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('experience_level', sa.String(length=30), nullable=False),
    sa.Column('primary_goal', sa.String(length=40), nullable=False),
    sa.Column('training_location', sa.String(length=40), nullable=False),
    sa.Column('available_days', sa.Integer(), nullable=False),
    sa.Column('session_minutes', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('workout_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=140), nullable=False),
    sa.Column('goal', sa.String(length=40), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('generation_reason', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workout_plans_user_id'), 'workout_plans', ['user_id'], unique=False)
    op.create_table('plan_sessions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('scheduled_date', sa.Date(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('estimated_minutes', sa.Integer(), nullable=False),
    sa.Column('focus', sa.String(length=80), nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['workout_plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_plan_sessions_plan_id'), 'plan_sessions', ['plan_id'], unique=False)
    op.create_table('user_equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'equipment_id')
    )
    op.create_table('user_restrictions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('profile_id', sa.Uuid(), nullable=False),
    sa.Column('restriction_id', sa.Uuid(), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['user_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['restriction_id'], ['restrictions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('profile_id', 'restriction_id')
    )
    op.create_table('session_exercises',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_order', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('repetitions', sa.String(length=30), nullable=False),
    sa.Column('rest_seconds', sa.Integer(), nullable=False),
    sa.Column('target_rpe', sa.Float(), nullable=False),
    sa.Column('recommended_weight_kg', sa.Float(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['plan_sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_session_exercises_session_id'), 'session_exercises', ['session_id'], unique=False)
    op.create_table('workout_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('session_id', sa.Uuid(), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actual_minutes', sa.Integer(), nullable=False),
    sa.Column('difficulty', sa.Integer(), nullable=False),
    sa.Column('energy_level', sa.Integer(), nullable=False),
    sa.Column('satisfaction', sa.Integer(), nullable=False),
    sa.Column('pain_reported', sa.Boolean(), nullable=False),
    sa.Column('pain_area', sa.String(length=80), nullable=False),
    sa.Column('comments', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['plan_sessions.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'session_id')
    )
    op.create_index(op.f('ix_workout_logs_session_id'), 'workout_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_workout_logs_user_id'), 'workout_logs', ['user_id'], unique=False)
    op.create_table('exercise_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('workout_log_id', sa.Uuid(), nullable=False),
    sa.Column('session_exercise_id', sa.Uuid(), nullable=False),
    sa.Column('exercise_id', sa.Uuid(), nullable=False),
    sa.Column('recommended_weight_kg', sa.Float(), nullable=False),
    sa.Column('actual_weight_kg', sa.Float(), nullable=False),
    sa.Column('completed_sets', sa.Integer(), nullable=False),
    sa.Column('completed_repetitions', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['session_exercise_id'], ['session_exercises.id'], ),
    sa.ForeignKeyConstraint(['workout_log_id'], ['workout_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workout_log_id', 'session_exercise_id')
    )
    op.create_index(op.f('ix_exercise_logs_exercise_id'), 'exercise_logs', ['exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_session_exercise_id'), 'exercise_logs', ['session_exercise_id'], unique=False)
    op.create_index(op.f('ix_exercise_logs_workout_log_id'), 'exercise_logs', ['workout_log_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercise_logs_workout_log_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_session_exercise_id'), table_name='exercise_logs')
    op.drop_index(op.f('ix_exercise_logs_exercise_id'), table_name='exercise_logs')
    op.drop_table('exercise_logs')
    op.drop_index(op.f('ix_workout_logs_user_id'), table_name='workout_logs')
    op.drop_index(op.f('ix_workout_logs_session_id'), table_name='workout_logs')
    op.drop_table('workout_logs')
    op.drop_index(op.f('ix_session_exercises_session_id'), table_name='session_exercises')
    op.drop_table('session_exercises')
    op.drop_table('user_restrictions')
    op.drop_table('user_equipment')
    op.drop_index(op.f('ix_plan_sessions_plan_id'), table_name='plan_sessions')
    op.drop_table('plan_sessions')
    op.drop_index(op.f('ix_workout_plans_user_id'), table_name='workout_plans')
    op.drop_table('workout_plans')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('restrictions')
    op.drop_table('exercises')
    op.drop_table('equipment')
    # ### end Alembic commands ###
